# This file contains all settings that are set at the start of the GUI application
# and reloaded if content changes during development.

box_label_font_size = 28.0
max_height_listing_table = 200.0
header_table_height =  20.0
ldap_multi_field_sep = "| "
title_font_size = 20.0
tooltip_size = 20.0
tooltip_symbol = "?"

[tooltiptexts]
ldap_creds = "LDAP credentials"
ldap_readonly_creds = "LDAP readonly credentials"
ssh_creds = "SSH credentials"
list_ldap_btn = "List users stored in LDAP database"
list_ssh_btn = "List users stored in Slurm database"
username = "Name used as the identifier to determine a specific user in the LDAP/Slurm database. Note: This must be unique among all users"
firstname = "Firstname of a user"
lastname = "Lastname of a user"
email = "Email address of the user"
pub_key = "SSH public key that is to be stored in LDAP"
group = "Name of group the user belongs to"
default_qos = "Default quality of service (QoS) of a user"
qos = "All QoS the user can use to run jobs"
conf_student_qos = "Default QoS for students"
conf_student_default_qos = "Which default Quality of service are used for a student"
conf_run_slurm_remote = "Run slurm command on remote nodes instead on your own local computer."
conf_ssh_port = "Port used for SSH connection"
conf_staff_default_qos = "Default value of the Slurm default QOS for the staff group"
conf_default_ssh_user = "Default user for SSH login during directory management"
conf_head_node = """Slurm head node (where sacctmgr is installed, remote or locally on the machine).
This is required if run_slurm_remote is true
"""
conf_nfs_host = "Hostname of an nfs server to be used by cluster users"
conf_nfs_root_dir = "Root directory of the shared folders on the nfs, aka network, host"
conf_valid_qos = """
A list of QOS against which user inputs are validated. 
Note that the set values must also exist as actual QOS in Slurm. 
"""
conf_staff_qos = "Default value of the Slurm QOS for the staff group"
conf_valid_slurm_groups = """A list of groups against which user inputs are validated. 
Note that the set values must also exist as actual Accounts in Slurm
"""
conf_compute_nodes = "Root directory of user folders on each compute node (must be the same on each node)"
conf_ldap_domain_components = """Domain components used for LDAP queries. They will be used in combination with ldap_org_unit 
and the cn of the username you provided for ldap login
"""
conf_ldap_org_unit = """Organizational unit used in the ID path within the LDAP tree.
This entry is combined with ldap_domain_components. 
Example: '[ldap_org_unit,]{ldap_domain_components}'.
Note: It is optional and can be omitted
"""
conf_ldap_bind_org_unit = """Used for a different OU for establishing connections to you LDAP server.
Note: Is optional and can be omitted.
The resulting ldap path for logging is: {ldap_bind_prefix}=<ldap_user_name>,[ldap_bind_prefix,][ldap_domain_components] 
"""
conf_ldap_bind_prefix = """User bind prefix to be used when establishing LDAP connections. 
Example of binding: \"cn=admin\" or \"uid=someuser\" .
"""
conf_ldap_readonly_user_prefix = """It is used for connection which have only read access.
Note: it is optional and can be omitted.
It is the user bind prefix to be used when establishing LDAP connections. 
Example of binding : cn=admin. or uid=someuser.
"""
conf_ldap_readonly_bind = """
It is used for connection with read access only.
The resulting ldap path for logging is: {ldap_bind_prefix}=<ldap_user_name>,[ldap_bind_prefix,][ldap_domain_components] .
Note: It is optional and can be omitted
"""
conf_ldap_server = "Protocol, host and port of your LDAP server"
conf_ldap_readonly_user = """Read only user for ldap search queries (e.g. usermgmt list ldap).
Note: Is optional and can be omitted
"""
conf_ldap_readonly_pw = "Read only user password and note it is optional and can be omitted"
conf_include_ldap = "If true then creating, deleting or modifying an user is also preformed on the LDAP data base"
conf_include_slurm = """If true then creating, deleting or modifying an user is also preformed on the slurm data base"""
conf_include_dir_mgmt = "Use the directory management module of the application"
conf_use_homedir_helper = "Use the mkhomedir_helper tool to create the user home directory (recommended)"
conf_ssh_agent = "If true, the application will try to authenticate via a ssh agent before the simple password authentication"
conf_compute_node_root_dir = "Root directory of user folders on each compute node (must be the same on each node)"
conf_filesystem = "Filesystem (or mountpoint) under which user quotas are to be set on the compute nodes"
conf_home_filesystem = "Filesystem (or mountpoint) under which user quotas on the user's home directory are to be set"
conf_nfs_filesystem = "Filesystem (or mountpoint) under which user quotas are to be set on the NFS"
conf_quota_softlimit = "Soft storage limit on the space for an user on compute nodes"
conf_quota_hardlimit = "Maximum amount of storage space that an user can use on compute nodes"
conf_quota_nfs_softlimit = """Amount of storage space which is not supposed to be exceeded within nfs, aka network, folder of an user. 
Storage usage is definitely capped at the value of quota_nfs_hardlimit"""
conf_quota_nfs_hardlimit = "Maximum amount of storage space within nfs, aka network, folder of an user"
conf_quota_home_softlimit = """Amount of storage space which is not supposed to be exceeded within the home folder of an user. 
Storage usage is definitely capped at the value of quota_home_hardlimit"""
conf_quota_home_hardlimit = "Maximum amount of storage space within the home folder of an user"
conf_login_shell = "Which shell is used for running LDAP/Slurm commands. Bash or fish is an examples of a shell"
conf_staff_gid = "Number to identify the group called \"Staff\""
conf_student_gid = "Number to identify the group called \"Student\""
conf_faculty_gid = "Number  value to identify the group called \"Faculty\""
conf_sacctmgr_path = "Path of the program usually named sacctmgr. That program is used to run the SLURM commands on your machine locally"

[texts]
conf_load_init_msg = "No configuration loaded yet"
conf_load_success_msg = "Configuration successfully loaded"
conf_load_err_msg = "Failed to load configuration."
conf_load_loading_msg = "Loading configuration"
conf_save_init_msg = "No configuration saved yet"
conf_save_success_msg = "Configuration successfully saved"
conf_save_err_msg = "Failed to save configuration"
conf_save_loading_msg = "Saving configuration"
conf_load_group = "Load Progress"
conf_save_group = "Save Progress"
ssh_cred = "SSH credentials"
ldap_cred = "LDAP credentials"
dir_conf_path = "Path to directory with the file called conf.toml"
general_status = "Status"
required = "Required"
optional = "Optional"
readonly_ldap_cred = "LDAP readonly credentials"
status_list_slurm = "Status of listing Slurm users"
status_list_ldap = "Status of listing LDAP users"
username = "Username"
password = "Password"
firstname = "Firstname"
lastname = "Lastname"
mail = "Email"
qos = "Quality of Services"
default_qos = "Default Quality of Services"
public_key = "Public Key"
group = "User group"
btn_action_conf_load = "Load"
btn_action_conf_save = "Save"
btn_action_conf_default = "Default"
btn_action_add = "Add User"
btn_action_remove = "Remove User"
btn_action_modify = "Modify User"
btn_list_ldap_users = "List LDAP Users"
btn_list_slurm_users = "List Slurm Users"
btn_list_remove = "Remove"
btn_new_item = "Add new Item"
listing_slurm_init = "No slurm user listed yet"
listing_slurm_loading = "Fetching slurm users"
listing_slurm_success = "Fetched Slurm users successfully"
listing_slurm_failure = "Failed to fetch Slurm users"
listing_ldap_init = "No LDAP user listed yet"
listing_ldap_loading = "Fetching LDAP users"
listing_ldap_success = "Fetched LDAP users successfully"
listing_ldap_failure = "Failed to fetch LDAP users"
modify_init = "No user modified yet:"
modify_loading = "Modifying user :"
modify_success = "Modified user successfully:"
modify_failure = "Failed to modify user :"
mode_main_title = "On which System"
mode_ldap = "LDAP"
mode_slurm = "Slurm"
mode_directory = "Directory"
failed_parsing_slurm = "Could not parse slurm users to a table"
ldap_cred_missing = "LDAP credentials are missing"
ssh_cred_missing = "Ssh credentials are missing"

[colors]
# [<red>, <green>, <blue>, <alpha>] all values 0-255.
# Red
err_msg = [255, 0, 0, 0]
# Blue
loading_msg = [0, 0, 255, 0]
# Green
success_msg = [0, 255, 0, 0]
# Gray
init_msg = [160, 160, 160, 0]
# Light Blue
tool_tip = [44, 194, 200, 255]
