# this configuration is set up for development 
# via docker container serving as end points for ldap and slurm nodes

# ldap bind for user is cn=admin,dc=example,dc=org in docker set up

ldap_add_created_at = true 
student_default_qos = 'basic'
staff_default_qos = 'advanced'
student_qos = ['interactive', 'basic', 'preemptible']
staff_qos = ['interactive', 'advanced', 'preemptible']
valid_qos = ['interactive', 'basic', 'advanced', 'preemptible']
valid_slurm_groups = ['staff', 'student']
objectclass_common = [
    'inetOrgPerson',
    'ldapPublicKey',
    'organizationalPerson',
    'person',
    'posixAccount',
    'shadowAccount',
    'slurmRole',
    'ldapAttributes',
    'top',
]
compute_nodes = ['ml0.host.de', 'ml1.host.de']
# Static ip address of docker container as head node for development
head_node = '172.25.0.13'
# Name of user with slurm admin rights in the slurmdb of the development docker set up.
default_ssh_user = 'dev_user'
# Static ip address of docker container as head node for development
home_host = '172.25.0.13'
nfs_host = ['nfs1.server.de', 'nfs2.server.de']
nfs_root_dir = ['/mnt/md0/scratch', '/mnt/md0/scratch']
compute_node_root_dir = '/mnt/md0/user'
filesystem = '/mnt/md0'
home_filesystem = '/dev/sdb4'
nfs_filesystem = ['/dev/sda1', '/dev/sda1']
quota_softlimit = '200G'
quota_hardlimit = '220G'
quota_nfs_softlimit = ['200G', '200G']
quota_nfs_hardlimit = ['220G', '220G']
quota_home_softlimit = '20G'
quota_home_hardlimit = '22G'
login_shell = '/bin/bash'
student_gid = 1002
staff_gid = 1001
faculty_gid = 1000
# In development the access to slurm is remote via a docker container
sacctmgr_path = 'sacctmgr'
ldap_domain_components = 'dc=example,dc=org'
ldap_org_unit = 'ou=people'
# ldap_bind_org_unit = 'ou=people'
# ldap_bind_prefix = ''
# ldap_readonly_user_prefix = "read_only_uid"
# ldap_readonly_bind = "ou=readonly,ou=realm"
ldap_server = 'ldap://localhost:389'
ldap_readonly_user = 'admin'
ldap_readonly_pw = 'admin'
include_slurm = true
include_ldap = true
include_dir_mgmt = false
# We do not support directory management in the docker development set up
use_homedir_helper = false
run_slurm_remote = true
ssh_agent = true
ssh_port = 22
# Path key pair of dev user with approbate rights to add/remove and modify users in the slurm db on the dev docker set up. 
ssh_key_path = "./docker/slurm-docker-cluster/dev_user_ed25519"
